config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth"}

  resources :reviews

  resources :books do

    member do
    end

    collection do
      post 'search'
      post 'publish'
    end

    resources :reviews do
      resources :comments
    end
  end

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, 
         :omniauth_providers => [:facebook]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  # GET /books
  # GET /books.json

  #def authenticate_user
  #  redirect_to "/nologin" unless cookies[:current_user]
  #end

  def login
    
  end

  def index
    if cookies[:second_time].nil?
      @message= "Bienvenido al Site"
      cookies[:second_time] = true
      #Para borrar cookies
      #cookies.delet(:second_time)
    end
  cookies.signed[:current_user]=10
    @books = Book.all.reverse
  end

  # GET /books/1
  # GET /books/1.json
  def show
    #CReando Sesiones
    if session[:safe]
      logger.info "Seguro"
    end
  end

  #Seahr
  def search


    filters = "%#{params[:terms]}%"
    @books = Book.where("title like ?", filters)
    render :index
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description)
    end
end

app/controllers/omniauth_controller.rb
class OmniauthController <ApplicationController

	def facebook
		#logger.info request.env["omniauth.auth"].info.image
		session[:image] = request.env["omniauth.auth"].info.image
		session[:name] = request.env["omniauth.auth"].info.name
		redirect_to books_path

	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def index
		if params[:book_id]
				@reviews = Review.where(book_id: params[:book_id])
			else
				@reviews = Review.all
		end
	end

	def new
		@review = Review.new(book_id: params[:book_id])
	end

	def create 
		@review = Review.new(review_params)
		@review.save
		redirect_to book_reviews_path(params[:book_id])
	end

	def review_poarams
		params.require(:review).permit(:title, :content, :author_name, :written_at, :raiting, :book_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

end

app/views/books/_books.html.erb
<div class='content'>
   <% @books.each do |book| %>
    <div class="contenido">
      <h1><%= book.title %></h1>
      <h2><%= book.description %></h2>
    </div>
    <% end %>
</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if user_signed_in? %>
  
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        

<% else %>
 <div class="cajalogin">
	<%= link_to "Logueate con facebook", user_omniauth_authorize_path(:facebook) %>
</div>

<% end %>

<div class='content'>
<div class="buscador">
  <%= form_tag search_books_path  , remote: true do %>
  <%= text_field_tag "terms" %>	
  <% end %>
</div>
<div class="profile">
	<% if session[:image] %>
		<h1>Hey, You Welcome <%= session[:name] %></h1>
		<%= image_tag session[:image] %> 
	<% end %>
</div>

<div id="books">
<%= render "books" %>
</div>

</div>

app/views/books/index.js.erb
$("#books").html("<%= j render 'books' %>")

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:alert] %>
<%= flash[:notice] %>
<%= yield %>

</body>
</html>

app/views/reviews/index.html.erb
Reviews xD

<%= link_to "Crear Review" , new_book_review_path %>

app/views/reviews/new.html.erb
CReate Review

<%= simple_form_for [:book, @review] do |f| %>
<%= f.input :title %>
<%= f.input :content %>
<%= f.input :author_name %>
<%= f.input :written_at %>
<%= f.input :raiting %>
<%= f.submit %>
<% end %>